Private chat
kisanola/tech-community pull request #11
Opened 2019-05-29 10:45 UTC by gracelungu

#### What does this PR do?
Adds a feature for users to send private messages to each other

#### Description of Task to be completed?
~ Create the chat model
~ Add the endpoint routes and controllers
~ Add a notifier helper to emit an event when the message is sent to a particular user
~ Write tests

#### How should this be manually tested?
The documentation provides the information to consume this API

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-05-30 07:09 UTC, Karlmusingo commented on src/controllers/AuthController.js
> +// import Token from '../models/Token';
remove this comment code

2019-05-30 07:39 UTC, Karlmusingo approved these changes

2019-05-30 07:57 UTC, oesukam requested changes

2019-05-30 07:57 UTC, oesukam commented on src/controllers/chatController.js
> +import { Chat } from '../models';
@gracelungu The controller's file name should be capitalized camel case as we are exporting a `Class`

2019-05-30 08:20 UTC, merged

2019-05-31 10:52 UTC, gracelungu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able to write privately to each other.](https://trello.com/c/iyoYfXjp/10-users-should-be-able-to-write-privately-to-each-other)