Implement following feature
kisanola/tech-community pull request #18
Opened 2019-06-03 10:43 UTC by Karlmusingo

#### What does this PR do?
enable users to follow each other
#### Description of Task to be completed?
- `POST /follow/:username`
- `DELETE /follow/:username`
#### How should this be manually tested?
- Clone the repo
- Run npm run test
#### Screenshots (if appropriate)

#### Questions:

2019-06-03 14:31 UTC, Karlmusingo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users should be able to follow each other](https://trello.com/c/oIiTShl8/7-users-should-be-able-to-follow-each-other)

2019-07-24 09:26 UTC, oesukam requested changes

2019-07-24 09:26 UTC, oesukam commented on src/__tests__/routes/follow.test.js
> +    // test('Should not follow a user who does not exist', async () => {
@Karlmusingo Why did you comment this block?

2019-07-24 09:26 UTC, oesukam commented on src/__tests__/routes/follow.test.js
> +// let user2;
Why this comment?

2019-08-26 06:09 UTC, merged