Add posts and jobs feeds
kisanola/tech-community pull request #22
Opened 2019-08-28 08:31 UTC by gracelungu

#### What does this PR do?
This PR adds the feeds for jobs and posts combined

#### Description of Task to be completed?
~ Add the feeds route and controller
~ Fetch combine and sort both posts and jobs by date

#### How should this be manually tested?
~ Fetch the branch and start the server
~ In the browser navigate to `localhost:3000/api/v1/feeds`

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-08-28 08:46 UTC, gracelungu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Get the landing page feeds](https://trello.com/c/Mh21Ij5o/32-get-the-landing-page-feeds)

2019-08-28 08:48 UTC, oesukam reviewed
@gracelungu Can't you also return feed related to organizations to be display on the side?

2019-08-28 08:50 UTC, gracelungu commented
@oesukam Do you mean adding an endpoint to get Organization feeds?

2019-08-28 08:50 UTC, oesukam commented on src/controllers/FeedsController.js
> +    const feeds = [...jobs, ...posts].sort(
@gracelungu What about pagination?

2019-09-05 13:10 UTC, oesukam requested changes

2019-09-05 13:10 UTC, oesukam commented on src/__tests__/routes/feeds.test.js
> +      expect(res.body.feeds).toEqual(expect.any(Array));
I think feed doesn't take an `s` in plural

2019-09-11 08:59 UTC, oesukam commented
@gracelungu Is Travis still failing?

2019-09-16 08:04 UTC, merged