Fixing time zone and testing cases
kisanola/tech-community pull request #39
Opened 2019-10-24 14:12 UTC by verdotte

#### What does this PR do?
fixing the time zone problem and follow test cases

#### Description of Task to be completed?
-implement a method for returning the current date & time according to the default time zone which is Africa/Kinshasa
-apply that method in all the models which capture the current date & time

#### How should this be manually tested?
Run npm test

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-11-05 10:55 UTC, gracelungu approved these changes

2019-11-05 11:03 UTC, gracelungu commented
@verdotte Good work. But try to improve your PR description.

2019-11-08 12:17 UTC, verdotte commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the issue with the date and update the TimeAgo component](https://trello.com/c/boaFJD2I/53-fix-the-issue-with-the-date-and-update-the-timeago-component)

2019-11-09 12:01 UTC, oesukam requested changes

2019-11-09 12:01 UTC, oesukam commented on src/helpers/defaultDateTime.js
> +export default defaultDateTime;
New line required at the end of each file

2020-04-26 10:12 UTC, oesukam approved these changes
LGTM

2020-04-26 10:12 UTC, merged